<a href="https://colab.research.google.com/github/manyasachdeva27/MACHINE-LEARNING/blob/main/Feature_construction_and_feature_splitting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

from sklearn.model_selection import cross_val_score
import seaborn as sns

In [3]:
df=pd.read_csv('/content/train.csv',usecols=['Age','Pclass','SibSp','Parch','Survived'])

In [4]:
df

     Survived  Pclass   Age  SibSp  Parch
0           0       3  22.0      1      0
1           1       1  38.0      1      0
2           1       3  26.0      0      0
3           1       1  35.0      1      0
4           0       3  35.0      0      0
..        ...     ...   ...    ...    ...
886         0       2  27.0      0      0
887         1       1  19.0      0      0
888         0       3   NaN      1      2
889         1       1  26.0      0      0
890         0       3  32.0      0      0

[891 rows x 5 columns]

In [5]:
df.dropna(inplace=True)

In [6]:
df.head()

   Survived  Pclass   Age  SibSp  Parch
0         0       3  22.0      1      0
1         1       1  38.0      1      0
2         1       3  26.0      0      0
3         1       1  35.0      1      0
4         0       3  35.0      0      0

In [8]:
x=df.drop(['Survived'],axis=1)
y=df['Survived']

In [9]:
x

     Pclass   Age  SibSp  Parch
0         3  22.0      1      0
1         1  38.0      1      0
2         3  26.0      0      0
3         1  35.0      1      0
4         3  35.0      0      0
..      ...   ...    ...    ...
885       3  39.0      0      5
886       2  27.0      0      0
887       1  19.0      0      0
889       1  26.0      0      0
890       3  32.0      0      0

[714 rows x 4 columns]

In [11]:
y

0      0
1      1
2      1
3      1
4      0
      ..
885    0
886    0
887    1
889    1
890    0
Name: Survived, Length: 714, dtype: int64

In [13]:
np.mean(cross_val_score(LogisticRegression(),x,y,scoring='accuracy',cv=20))

np.float64(0.6933333333333332)

Applying feature construction

In [15]:
x['family_size']=x['SibSp']+x['Parch']+1 # +1 because uss family member(khud ko) bhi to add karna hoga

In [16]:
def myfunc(num):
    if num == 1:
        #alone
        return 0
    elif num >1 and num <=4:
        # small family
        return 1
    else:
        # large family
        return 2

In [17]:
myfunc(4)

1

In [19]:
x['Family_type'] = x['family_size'].apply(myfunc)

In [21]:
x.head()

   Pclass   Age  SibSp  Parch  family_size  Family_type
0       3  22.0      1      0            2            1
1       1  38.0      1      0            2            1
2       3  26.0      0      0            1            0
3       1  35.0      1      0            2            1
4       3  35.0      0      0            1            0

In [22]:
x.drop(columns=['SibSp','Parch','family_size'],inplace=True)

In [23]:
x.head()

   Pclass   Age  Family_type
0       3  22.0            1
1       1  38.0            1
2       3  26.0            0
3       1  35.0            1
4       3  35.0            0

In [25]:
np.mean(cross_val_score(LogisticRegression(),x,y,scoring='accuracy',cv=20)) #improved

np.float64(0.7003174603174602)

Feature splitting

In [26]:
df=pd.read_csv('/content/train.csv')

In [27]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [28]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [30]:
df['Name'].str.split(',',expand=True)

             0                                            1
0       Braund                              Mr. Owen Harris
1      Cumings   Mrs. John Bradley (Florence Briggs Thayer)
2    Heikkinen                                  Miss. Laina
3     Futrelle           Mrs. Jacques Heath (Lily May Peel)
4        Allen                            Mr. William Henry
..         ...                                          ...
886   Montvila                                  Rev. Juozas
887     Graham                         Miss. Margaret Edith
888   Johnston               Miss. Catherine Helen "Carrie"
889       Behr                              Mr. Karl Howell
890     Dooley                                  Mr. Patrick

[891 rows x 2 columns]

In [31]:
df['Title']=df['Name'].str.split(',',expand=True)[1].str.split('.',expand=True)[0]

In [33]:
df['Title']

0         Mr
1        Mrs
2       Miss
3        Mrs
4         Mr
       ...
886      Rev
887     Miss
888     Miss
889       Mr
890       Mr
Name: Title, Length: 891, dtype: object

In [34]:
df[['Title','Name']]

     Title                                               Name
0       Mr                            Braund, Mr. Owen Harris
1      Mrs  Cumings, Mrs. John Bradley (Florence Briggs Th...
2     Miss                             Heikkinen, Miss. Laina
3      Mrs       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4       Mr                           Allen, Mr. William Henry
..     ...                                                ...
886    Rev                              Montvila, Rev. Juozas
887   Miss                       Graham, Miss. Margaret Edith
888   Miss           Johnston, Miss. Catherine Helen "Carrie"
889     Mr                              Behr, Mr. Karl Howell
890     Mr                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [36]:
df.groupby('Title')['Survived'].mean().sort_values(ascending=False)

Title
Lady            1.000000
Ms              1.000000
Sir             1.000000
Mme             1.000000
the Countess    1.000000
Mlle            1.000000
Mrs             0.792000
Miss            0.697802
Master          0.575000
Major           0.500000
Col             0.500000
Dr              0.428571
Mr              0.156673
Capt            0.000000
Jonkheer        0.000000
Don             0.000000
Rev             0.000000
Name: Survived, dtype: float64

In [37]:
df['Is_Married'] = 0
df['Is_Married'].loc[df['Title'] == 'Mrs'] = 1

/tmp/ipython-input-416/2254989826.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Is_Married'].loc[df['Title'] == 'Mrs'] = 1
/tmp/ipython-input-416/2254989826.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Is_Married'].loc[df['Title'] == 'Mrs'] = 1

In [38]:
df['Is_Married']

0      0
1      0
2      0
3      0
4      0
      ..
886    0
887    0
888    0
889    0
890    0
Name: Is_Married, Length: 891, dtype: int64