<a href="https://colab.research.google.com/github/manyasachdeva27/MACHINE-LEARNING/blob/main/Working_with_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#importing pandas
import pandas as pd

In [6]:
#opening a local csv file
df=pd.read_csv('/content/DailyDelhiClimateTrain.csv')

In [7]:
df

            date   meantemp    humidity  wind_speed  meanpressure
0     2013-01-01  10.000000   84.500000    0.000000   1015.666667
1     2013-01-02   7.400000   92.000000    2.980000   1017.800000
2     2013-01-03   7.166667   87.000000    4.633333   1018.666667
3     2013-01-04   8.666667   71.333333    1.233333   1017.166667
4     2013-01-05   6.000000   86.833333    3.700000   1016.500000
...          ...        ...         ...         ...           ...
1457  2016-12-28  17.217391   68.043478    3.547826   1015.565217
1458  2016-12-29  15.238095   87.857143    6.000000   1016.904762
1459  2016-12-30  14.095238   89.666667    6.266667   1017.904762
1460  2016-12-31  15.052632   87.000000    7.325000   1016.100000
1461  2017-01-01  10.000000  100.000000    0.000000   1016.000000

[1462 rows x 5 columns]

In [8]:
#opening a csv file from a URL

import requests
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers) #requets.get to fetch all the content form the website
data = StringIO(req.text) #req.text to fetch all the text only form the website

df = pd.read_csv(data)
df

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

In [9]:
#sep parameter for tsv files use pd.read_csv('/content/city_temperature.tsv',sep='/t')

In [12]:
#index_col paramter
pd.read_csv('/content/DailyDelhiClimateTrain.csv',index_col='date') #index_col aisa colum hoga jo aapke analysis me kaam nhi aane vala just for unique id

             meantemp    humidity  wind_speed  meanpressure
date
2013-01-01  10.000000   84.500000    0.000000   1015.666667
2013-01-02   7.400000   92.000000    2.980000   1017.800000
2013-01-03   7.166667   87.000000    4.633333   1018.666667
2013-01-04   8.666667   71.333333    1.233333   1017.166667
2013-01-05   6.000000   86.833333    3.700000   1016.500000
...               ...         ...         ...           ...
2016-12-28  17.217391   68.043478    3.547826   1015.565217
2016-12-29  15.238095   87.857143    6.000000   1016.904762
2016-12-30  14.095238   89.666667    6.266667   1017.904762
2016-12-31  15.052632   87.000000    7.325000   1016.100000
2017-01-01  10.000000  100.000000    0.000000   1016.000000

[1462 rows x 4 columns]

In [13]:
#Header parameter
#jab humne first row ko column ke names me convert hota h
pd.read_csv('/content/DailyDelhiClimateTrain.csv',header=1) #header=1 aapka jo first row h vo 1 se start hho rahi h

      2013-01-01       10.0        84.5       0.0  1015.6666666666666
0     2013-01-02   7.400000   92.000000  2.980000         1017.800000
1     2013-01-03   7.166667   87.000000  4.633333         1018.666667
2     2013-01-04   8.666667   71.333333  1.233333         1017.166667
3     2013-01-05   6.000000   86.833333  3.700000         1016.500000
4     2013-01-06   7.000000   82.800000  1.480000         1018.000000
...          ...        ...         ...       ...                 ...
1456  2016-12-28  17.217391   68.043478  3.547826         1015.565217
1457  2016-12-29  15.238095   87.857143  6.000000         1016.904762
1458  2016-12-30  14.095238   89.666667  6.266667         1017.904762
1459  2016-12-31  15.052632   87.000000  7.325000         1016.100000
1460  2017-01-01  10.000000  100.000000  0.000000         1016.000000

[1461 rows x 5 columns]

In [15]:
#use_cols parameter
pd.read_csv('/content/DailyDelhiClimateTrain.csv',usecols=['date','wind_speed','meantemp'])

            date   meantemp  wind_speed
0     2013-01-01  10.000000    0.000000
1     2013-01-02   7.400000    2.980000
2     2013-01-03   7.166667    4.633333
3     2013-01-04   8.666667    1.233333
4     2013-01-05   6.000000    3.700000
...          ...        ...         ...
1457  2016-12-28  17.217391    3.547826
1458  2016-12-29  15.238095    6.000000
1459  2016-12-30  14.095238    6.266667
1460  2016-12-31  15.052632    7.325000
1461  2017-01-01  10.000000    0.000000

[1462 rows x 3 columns]

In [17]:
#skip rows/ nrows parameter
pd.read_csv('/content/DailyDelhiClimateTrain.csv',skiprows=[1,2])

            date   meantemp    humidity  wind_speed  meanpressure
0     2013-01-03   7.166667   87.000000    4.633333   1018.666667
1     2013-01-04   8.666667   71.333333    1.233333   1017.166667
2     2013-01-05   6.000000   86.833333    3.700000   1016.500000
3     2013-01-06   7.000000   82.800000    1.480000   1018.000000
4     2013-01-07   7.000000   78.600000    6.300000   1020.000000
...          ...        ...         ...         ...           ...
1455  2016-12-28  17.217391   68.043478    3.547826   1015.565217
1456  2016-12-29  15.238095   87.857143    6.000000   1016.904762
1457  2016-12-30  14.095238   89.666667    6.266667   1017.904762
1458  2016-12-31  15.052632   87.000000    7.325000   1016.100000
1459  2017-01-01  10.000000  100.000000    0.000000   1016.000000

[1460 rows x 5 columns]

In [18]:
pd.read_csv('/content/DailyDelhiClimateTrain.csv',nrows=2)

         date  meantemp  humidity  wind_speed  meanpressure
0  2013-01-01      10.0      84.5        0.00   1015.666667
1  2013-01-02       7.4      92.0        2.98   1017.800000

In [19]:
#Encoding parameter used for datasets not encoded with utf-8 like datasets like hindi datasets, emoji datasets
pd.read_csv('/content/DailyDelhiClimateTrain.csv',encoding='latin-1')

            date   meantemp    humidity  wind_speed  meanpressure
0     2013-01-01  10.000000   84.500000    0.000000   1015.666667
1     2013-01-02   7.400000   92.000000    2.980000   1017.800000
2     2013-01-03   7.166667   87.000000    4.633333   1018.666667
3     2013-01-04   8.666667   71.333333    1.233333   1017.166667
4     2013-01-05   6.000000   86.833333    3.700000   1016.500000
...          ...        ...         ...         ...           ...
1457  2016-12-28  17.217391   68.043478    3.547826   1015.565217
1458  2016-12-29  15.238095   87.857143    6.000000   1016.904762
1459  2016-12-30  14.095238   89.666667    6.266667   1017.904762
1460  2016-12-31  15.052632   87.000000    7.325000   1016.100000
1461  2017-01-01  10.000000  100.000000    0.000000   1016.000000

[1462 rows x 5 columns]

In [20]:
#Skip bad lines (parser error)
#kuch aise datasets jinme beech beech me kuch rows me gadbad aayega jaise sab rows me 5 values but ek do rows me 6 values to vo read nahi kar pata h pandas
pd.read_csv('/content/DailyDelhiClimateTrain.csv',on_bad_lines='skip')

            date   meantemp    humidity  wind_speed  meanpressure
0     2013-01-01  10.000000   84.500000    0.000000   1015.666667
1     2013-01-02   7.400000   92.000000    2.980000   1017.800000
2     2013-01-03   7.166667   87.000000    4.633333   1018.666667
3     2013-01-04   8.666667   71.333333    1.233333   1017.166667
4     2013-01-05   6.000000   86.833333    3.700000   1016.500000
...          ...        ...         ...         ...           ...
1457  2016-12-28  17.217391   68.043478    3.547826   1015.565217
1458  2016-12-29  15.238095   87.857143    6.000000   1016.904762
1459  2016-12-30  14.095238   89.666667    6.266667   1017.904762
1460  2016-12-31  15.052632   87.000000    7.325000   1016.100000
1461  2017-01-01  10.000000  100.000000    0.000000   1016.000000

[1462 rows x 5 columns]

In [21]:
from numpy import int64
#dtypes parameter
pd.read_csv('/content/DailyDelhiClimateTrain.csv').info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1462 entries, 0 to 1461
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1462 non-null   object
 1   meantemp      1462 non-null   float64
 2   humidity      1462 non-null   float64
 3   wind_speed    1462 non-null   float64
 4   meanpressure  1462 non-null   float64
dtypes: float64(4), object(1)
memory usage: 57.2+ KB

In [22]:
pd.read_csv('/content/DailyDelhiClimateTrain.csv',dtype={'Day':int})

            date   meantemp    humidity  wind_speed  meanpressure
0     2013-01-01  10.000000   84.500000    0.000000   1015.666667
1     2013-01-02   7.400000   92.000000    2.980000   1017.800000
2     2013-01-03   7.166667   87.000000    4.633333   1018.666667
3     2013-01-04   8.666667   71.333333    1.233333   1017.166667
4     2013-01-05   6.000000   86.833333    3.700000   1016.500000
...          ...        ...         ...         ...           ...
1457  2016-12-28  17.217391   68.043478    3.547826   1015.565217
1458  2016-12-29  15.238095   87.857143    6.000000   1016.904762
1459  2016-12-30  14.095238   89.666667    6.266667   1017.904762
1460  2016-12-31  15.052632   87.000000    7.325000   1016.100000
1461  2017-01-01  10.000000  100.000000    0.000000   1016.000000

[1462 rows x 5 columns]

In [23]:
#Handling Dates
#dates are always passed in stripg (object format) so we have to convert them in date time format
pd.read_csv('/content/DailyDelhiClimateTrain.csv',parse_dates=['date'])

           date   meantemp    humidity  wind_speed  meanpressure
0    2013-01-01  10.000000   84.500000    0.000000   1015.666667
1    2013-01-02   7.400000   92.000000    2.980000   1017.800000
2    2013-01-03   7.166667   87.000000    4.633333   1018.666667
3    2013-01-04   8.666667   71.333333    1.233333   1017.166667
4    2013-01-05   6.000000   86.833333    3.700000   1016.500000
...         ...        ...         ...         ...           ...
1457 2016-12-28  17.217391   68.043478    3.547826   1015.565217
1458 2016-12-29  15.238095   87.857143    6.000000   1016.904762
1459 2016-12-30  14.095238   89.666667    6.266667   1017.904762
1460 2016-12-31  15.052632   87.000000    7.325000   1016.100000
1461 2017-01-01  10.000000  100.000000    0.000000   1016.000000

[1462 rows x 5 columns]

In [25]:
#Convertors
pd.read_csv('/content/DailyDelhiClimateTrain.csv',converters={'meantemp':lambda x:float(x)/100})

            date  meantemp    humidity  wind_speed  meanpressure
0     2013-01-01  0.100000   84.500000    0.000000   1015.666667
1     2013-01-02  0.074000   92.000000    2.980000   1017.800000
2     2013-01-03  0.071667   87.000000    4.633333   1018.666667
3     2013-01-04  0.086667   71.333333    1.233333   1017.166667
4     2013-01-05  0.060000   86.833333    3.700000   1016.500000
...          ...       ...         ...         ...           ...
1457  2016-12-28  0.172174   68.043478    3.547826   1015.565217
1458  2016-12-29  0.152381   87.857143    6.000000   1016.904762
1459  2016-12-30  0.140952   89.666667    6.266667   1017.904762
1460  2016-12-31  0.150526   87.000000    7.325000   1016.100000
1461  2017-01-01  0.100000  100.000000    0.000000   1016.000000

[1462 rows x 5 columns]

In [26]:
#na_values parameter
pd.read_csv('/content/DailyDelhiClimateTrain.csv',na_values=['Nan','nan','na-n'])

            date   meantemp    humidity  wind_speed  meanpressure
0     2013-01-01  10.000000   84.500000    0.000000   1015.666667
1     2013-01-02   7.400000   92.000000    2.980000   1017.800000
2     2013-01-03   7.166667   87.000000    4.633333   1018.666667
3     2013-01-04   8.666667   71.333333    1.233333   1017.166667
4     2013-01-05   6.000000   86.833333    3.700000   1016.500000
...          ...        ...         ...         ...           ...
1457  2016-12-28  17.217391   68.043478    3.547826   1015.565217
1458  2016-12-29  15.238095   87.857143    6.000000   1016.904762
1459  2016-12-30  14.095238   89.666667    6.266667   1017.904762
1460  2016-12-31  15.052632   87.000000    7.325000   1016.100000
1461  2017-01-01  10.000000  100.000000    0.000000   1016.000000

[1462 rows x 5 columns]

In [27]:
#Loading a huge dataset in chunks
dffs=pd.read_csv('/content/DailyDelhiClimateTrain.csv',chunksize=10000)
#ab aapko jo bhi kaam karna h ape dataframe ske upar aap loop me karoge

In [28]:
for chunk in dffs:
  print(chunk)

            date   meantemp    humidity  wind_speed  meanpressure
0     2013-01-01  10.000000   84.500000    0.000000   1015.666667
1     2013-01-02   7.400000   92.000000    2.980000   1017.800000
2     2013-01-03   7.166667   87.000000    4.633333   1018.666667
3     2013-01-04   8.666667   71.333333    1.233333   1017.166667
4     2013-01-05   6.000000   86.833333    3.700000   1016.500000
...          ...        ...         ...         ...           ...
1457  2016-12-28  17.217391   68.043478    3.547826   1015.565217
1458  2016-12-29  15.238095   87.857143    6.000000   1016.904762
1459  2016-12-30  14.095238   89.666667    6.266667   1017.904762
1460  2016-12-31  15.052632   87.000000    7.325000   1016.100000
1461  2017-01-01  10.000000  100.000000    0.000000   1016.000000

[1462 rows x 5 columns]